# SiameseX

== What you'll build
 
In this guide, you will build a web form of Siamese which will be accessible at the following URL:

    http://localhost:8080/greeting

Viewing this page in a browser will display the form. You can submit a search query by putting a code snippet to search for clones in the form. A results page will be displayed when the form is submitted.


== What you'll need

* Java version 1.8
* Elasticsearch version 2.2.0 (already provided in this repo)


[[initial]]
== Run a web controller

1) Clone the repo and open the project (SiameseX/webapp) in IntelliJ IDEA (tested) or Eclipse (not tested).

2) Extract elasticsearch-2.2.0-small.zip.

3) Open a new terminal, nativate to the extracted elasticsearch folder, and run elasticsearch.

```bash
./bin/elasticsearch
```

4) Inside IntelliJ IDEA, go to terminal and run

```bash
./mvnw spring-boot:run
```

5) Wait until the compilation is completed, then open a web browser and go to: [http://localhost:8080/greeting](http://localhost:8080/greeting)
6) Try to enter a code snippet in the search form and press search.

